openapi: 3.0.3
info:
  version: 1.0.0
  title: service-registry
  description: This service is designed to register new services
servers:
  - url: /registry
paths:
  /service:
    post:
      operationId: registerService
      tags:
        - service
      summary: Create a new service record within the registry
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Service'
      responses:
        201:
          description: Successfully registered a service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'

    get:
      operationId: ListRegisteredServices
      tags:
        - service
      summary: Obtain a list of all registered services
      responses:
        200:
          description: Retrieved a list of services
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Service'

  /services/{serviceId}:
    get:
      summary: Retrieve a specific service
      operationId: getService
      parameters:
        - name: serviceId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Service found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
        404:
          description: Service not found

    put:
      summary: Update a specific service
      operationId: updateService
      parameters:
        - name: serviceId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Service'
      responses:
        200:
          description: Service updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
        404:
          description: Service not found

    delete:
      summary: Delete a specific service
      operationId: deleteService
      parameters:
        - name: serviceId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        204:
          description: Service deleted
        404:
          description: Service not found

components:
  schemas:
    Service:
      type: object
      additionalProperties: false
      required:
        - name
        - baseUrl
        - description
      properties:
        name:
          type: string
          description: The name of the service
          example: access
        baseUrl:
          type: string
          description: The base url to access the service
        description:
          type: string
          maxLength: 200
          description: A short description of the service
        healthcheckUrl:
          type: string
          description: An optional healthcheck endpoint that can be used to allow the service registry to periodically check the whether a service is healthy
